name: Daily Notification

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bash
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Execute script
      run: |
        bash -c '
        YOUR_PUSHPLUS_TOKEN="$YOUR_PUSHPLUS_TOKEN"
        ./qndxx.sh
        '
      env:
        YOUR_PUSHPLUS_TOKEN: ${{ secrets.YOUR_PUSHPLUS_TOKEN }}
