name: Daily Notification

on:
  schedule:
    - cron: "25 12,13,15 * * *"  # 时间执行
  workflow_dispatch:  # 允许手动触发

      
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bash
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: Execute pushplus
        env:
          YOUR_PUSHPLUS_TOKEN: ${{ secrets.YOUR_PUSHPLUS_TOKEN }} 
        run: bash qndxx.sh
      #- name: Execute xizhi.sh 
      #  env:
      #    XIZHI_TOKEN: ${{ secrets.XIZHI_TOKEN }}  
      #  run: bash xizhi.sh
        
        
      #- name: Execute wxpusher.sh
      #  run: |
      #    chmod +x wxpusher.sh
      #    ./wxpusher.sh
      #  env:
      #    wxpusher_token: ${{ secrets.wxpusher_token }}   另加脚本和环境变量
#on: 
#  schedule: 
#    - cron: '25 12,13,15 * * *'  # 时间执行
#  workflow_dispatch:  # 允许手动触发
#    inputs: 
#      manual_trigger: 
#        description: '手动触发工作流'
#        required: false 
#
#  push:
#    paths:
#      - '.github/workflows/main.yml'  # 当 main.yml 文件发生变化时触发
